# contents of pyproject.toml

[project]
name = "package"
version = "0.1.0"
dependencies = [
    "numpy"
]

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"