# contents of pyproject.toml

[project]
name = "package"
dependencies = [
    "numpy"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["hatchling", "hatch-vcs"]

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/package/__init__.py"