on:
  pull_request:
  push:
      branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install package
      run: python -m pip install -e .[test]
    - name: Test package
      run: python -m pytest
